### PR TITLE
Update translation.php - Fix: Wrong path in the function load_translations #362

### PR DESCRIPTION
**Pull request by benny-ben**
Hi Jeremy I don't know if it's the correct way open issue and pull request

https://github.com/JeremyEnglert/JointsWP/issues/362

### CODE REVIEW

**Comment by garretthyder** [comment]
Hi @benny-ben your PR here is merging into your own project. You need to either update this PR to merge into JeremyEnglert/JointsWP or recreate the PR.
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by benny-ben** [comment]
Hi @garrett-eclipse  thanks for the link (these are my first PR on GitHub).
I try to merge pull request in the repository JeremyEnglert/JointsWP
https://github.com/JeremyEnglert/JointsWP/pull/363
I hope it goes well

**Comment by garretthyder** [comment]
Thanks that worked, you can close this PR on your own project as it's in the master.

**Comment by benny-ben** [comment]
Thanks @garrett-eclipse I did it

**Pull request merged**
